const Questions = [
	[],
	{
		question: "What is your primary area of expertise in tech ?",
		answers: [
			"Software Engineer [FrontEnd]",
			"Software Engineer [BackEnd]",
			"Web Developer [FrontEnd]",
			"Web Developer[BackEnd]",
			"UI/UX Developer",
			"Graphic Designer",
			"Data Scientist",
			"CyberSecurity Engineer",
		],
	},
	{
		question: "How many years of experience do you have as a ",
		answers: [
			"Less than a year",
			"1 - 2 years",
			"3 - 5 years",
			"6 - 10 years",
			"More 10 years",
		],
	},
	{
		question: "Which of the following tools do you use fondly as a ",
		answers: [
			[
				"HTML",
				"CSS",
				"JavaScript",
				"TypeScript",
				"Python",
				"JSX",
				"Dart",
				"Elm",
				"CoffeeScript",
				"Haml",
				"Sass",
				"Less",
				"Stylus",
				"Pug",
				"Handlebars",
				"Mustache",
				"Swift",
				"Java",
				"Kotlin",
				"Dart",
				"Objective-C",
			],
			[
				"Java",
				"Python",
				"Node.js",
				"Ruby",
				"PHP",
				"C#",
				"Go",
				"Scala",
				"Kotlin",
				"Rust",
				"Swift (Vapor framework)",
				"Perl",
				"Lua",
				"R",
				"SQL",
			],
			[
				"Sketch",
				"Figma",
				"Adobe XD",
				"InVision",
				"Axure",
				"Balsamiq",
				"Marvel",
				"Principle",
				"Zeplin",
				"Sketchbook",
				"Procreate",
				"Affinity Designer",
				"Adobe Photoshop",
				"Adobe Illustrator",
				"Adobe Creative Cloud",
			],
			[
				"Adobe Photoshop",
				"Adobe Illustrator",
				"Adobe InDesign",
				"Sketch",
				"Canva",
				"CorelDRAW",
				"Affinity Designer",
				"Figma",
				"Adobe Creative Cloud",
				"Inkscape",
				"GIMP",
				"Gravit Designer",
				"Adobe Spark",
				"Piktochart",
			],
			[
				"Python",
				"R",
				"SQL",
				"Tableau",
				"Jupyter Notebook",
				"Apache Spark",
				"TensorFlow",
				"PyTorch",
				"Apache Kafka",
				"Hadoop",
				"Scikit-learn",
				"Apache HBase",
				"Apache Hive",
				"Apache Cassandra",
				"RapidMiner",
			],
			[
				"Nmap",
				"Wireshark",
				"Metasploit",
				"Burp Suite",
				"Kali Linux",
				"Nessus",
				"Snort",
				"Aircrack-ng",
				"John the Ripper",
				"OpenVAS",
				"Cain and Abel",
				"Nikto",
				"Hydra",
				"Hashcat",
				"OWASP ZAP",
			],
		],
	},
	{
		question: "What's your favorite way to stay organized ?",
		answers: [
			"Writing a to-do list on paper",
			"Using a task management app",
			"Using a whiteboard",
			"Keeping everything in my head",
		],
	},

	{
		question:
			"What is the most important factor to you when choosing a new job in the tech industry ?",
		answers: [
			"Salary",
			"Company culture",
			"Work-life balance",
			"Opportunity for growth",
		],
	},
	{
		question:
			"What is your preferred method of staying up to date with industry news and trends ?",
		answers: [
			"Reading tech blogs and news sites",
			"Attending industry conferences and events",
			"Listening to podcasts or watching videos",
			"Networking with other professionals",
		],
	},
	{
		question:
			"What is the most important factor to you when choosing a new laptop or computer ?",
		answers: [
			"Performance and processing power",
			"Portability and battery life",
			"Display quality and resolution",
			"Price and value for money",
		],
	},
	{
		question:
			"What is the biggest challenge you face when working remotely or from home ?",
		answers: [
			"Distractions and staying focused",
			"Maintaining work-life balance",
			"Communicating and collaborating with colleagues",
			"I dont work from home",
		],
	},
	{
		question: "What's your favorite tech-themed TV show ?",
		answers: [
			"Silicon Valley",
			"Mr. Robot",
			"Black Mirror",
			"The Big Bang Theory",
			"Star Trek",
			"The IT Crowd",
			"Halt and Catch Fire",
		],
	},
	{
		question: "What's your favorite keyboard shortcut ?",
		answers: ["Ctrl+C", "Ctrl+V", "Ctrl+Z", "Ctrl+Shift+T"],
	},
	{
		question:
			"How do you like to unwind after a long day of building/working ?",
		answers: [
			"Watching TV",
			"Playing video games",
			"Reading a book",
			"Going for a run",
		],
	},
	{
		question: "What are your favorite tech gadgets ?",
		answers: [
			"Smartphone",
			"Laptop",
			"Tablet",
			"Smartwatch",
			"Fitness Tracker",
			"Gaming Console",
			"Wireless Headphones",
			"Smart Speaker",
			"Streaming Device",
			"Virtual Reality Headset:",
		],
	},
	{
		question: "Apple Or Windows Laptop ?",
		answers: ["Apple", "Windows"],
	},
	{
		question: "Which one of the following operating systems do you prefer ?",
		answers: ["Windows", "MacOS", "Linux", "Kali Linux", "Ubuntu"],
	},
	{
		question: "What type of projects do you enjoy working on the most ?",
		answers: [
			"FrontEnd Web Development",
			"BackEnd Web Development",
			"Fullstack Web Developments",
			"FrontEnd Software Engineering",
			"BackEnd Software Engineering",
			"Fullstack Software Engineering",
			"Fullstack Mobile App Development",
			"FrontEnd Mobile App Development",
			"BackEnd Mobile App Development",
			"Machine learning",
			"UI/UX design",
		],
	},
	{
		question: "How do you prefer to learn new technology ?",
		answers: [
			"Online courses",
			"Documentation",
			"Tutorials",
			"Trial and error",
		],
	},
	{
		question: "How many hours a day do you spend on your computer ?",
		answers: [
			"Less than 2 hours",
			"2-4 hours",
			"4-6 hours",
			"More than 6 hours",
		],
	},
	{
		question:
			"How long did it take you to get your first job/gig after starting your tech career ?",
		answers: [
			"Less than a year",
			"1 - 2 years",
			"2 - 4 years",
			"above 4 years",
		],
	},
	{
		question: "How do you stay productive while working from home ?",
		answers: [
			"Setting up a dedicated workspace",
			"Establishing a routine and sticking to it",
			"Taking breaks regularly",
			"All of the above",
		],
	},
	{
		question: "How often do you feel burned out at work ?",
		answers: [
			"Every day",
			"A few times a week",
			"Once a week",
			" Once a month",
			"Rarely",
		],
	},
	{
		question:
			"How many hours of sleep do you typically get each night during the workweek ?",
		answers: [
			"Less than 5 hours",
			"5-6 hours",
			"6-7 hours",
			"7-8 hours",
			"More than 8 hours",
		],
	},
	{
		question: "How often do you work on the weekends ?",
		answers: [
			"Every weekend",
			"Every other weekend",
			"Once a month",
			"Rarely",
			"Never",
		],
	},
];

export const feedBacks = ["💜", "🤣", "😘", "😡", "🫥"];
export default Questions;
